[build]
publish = "."

[[redirects]]
from = "/dashboard"
to = "/"
status = 301

[[redirects]]
from = "/ranking"
to = "/ranking_modelos_ultimas4.html"
status = 301

[[redirects]]
from = "/efeito"
to = "/efeito_jogadores.html"
status = 301

[[redirects]]
from = "/premiacao"
to = "/premiacao_mensal.html"
status = 301

[[redirects]]
from = "/ranking-geral"
to = "/ranking_geral_jogadores.html"
status = 301

[[redirects]]
from = "/raio-x"
to = "/raio_x_jogador.html"
status = 301

[[redirects]]
from = "/sugestao-notas"
to = "/sugestao_novas_notas.html"
status = 301

[[redirects]]
from = "/detalhe-notas"
to = "/detalhe_recomendacoes_notas.html"
status = 301
